language: ruby
services: mysql
rvm:
  - 2.0.0
  
before_script:
  - mysql -e 'create database lessonable_test;'
  
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - HIT_STRIPE=true bundle exec rspec spec